import { LowerCasePipe } from '@angular/common';
// Generated by https://quicktype.io

import { TruthToPlotSource, TruthToPlotValue } from './truth-to-plot';

// export enum QuantileType{
//   Q95Lower = '0.025',
//   Q95Upper = '0.095',

//   Q50Lower = '0.25',
//   Q50Upper = '0.75'
// }

export enum QuantileType {
  Q95,
  Q50
}

export enum QuantilePointType {
  Lower,
  Upper
}

export enum ForecastToPlotType {
  Observed = 'observed',
  Point = 'point',
  Quantile = 'quantile'
}

export interface ForecastToPlotTarget {
  time_ahead: number;
  time_unit: 'day' | 'wk';
  value_type: TruthToPlotValue;
  end_date: moment.Moment;
}

export interface ForecastToPlot {
  forecast_date: moment.Moment;
  target: ForecastToPlotTarget;
  location: string;
  type: ForecastToPlotType;
  quantile: { type: QuantileType, point: QuantilePointType };
  value: number;
  timezero: moment.Moment;
  model: string;
  truth_data_source: TruthToPlotSource;
  shifts: Map<TruthToPlotSource, number>;
  first_commit_date: moment.Moment;
}
